name: build-assets

on:
  push:
    branches: [main, staging]

jobs:
  build-assets:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build assets
        run: |
          npm run build

      - name: Pull changes
        run: git pull

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.pull_request.base.ref }}
          commit_message: >
            build assets
